/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Vista;

import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class vistaRegistro extends javax.swing.JPanel {

    /** Creates new form vistaRegistro */
    public vistaRegistro() {
        initComponents();
    }

    public JButton getBtn_registrar() {
        return btn_registrar;
    }

    public void setBtn_registrar(JButton btn_registrar) {
        this.btn_registrar = btn_registrar;
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPersona = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblsApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_pApellido = new javax.swing.JTextField();
        txt_sApellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        lblMascota = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txt_nombreM = new javax.swing.JTextField();
        txt_raza = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btn_examinar = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();
        lblIcoP = new javax.swing.JLabel();
        lblIcoM = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(853, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar_32px.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar_32px.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar_32px.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 42));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPersona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPersona.setText("Persona");
        jPanel1.add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblNombreP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreP.setText("Nombre");
        jPanel1.add(lblNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApellido.setText("Primer Apellido");
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));

        lblsApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblsApellido.setText("Segundo Apellido");
        jPanel1.add(lblsApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelefono.setText("Telefono");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDireccion.setText("Dirección");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, -1));
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));
        jPanel1.add(txt_pApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));
        jPanel1.add(txt_sApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, -1));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, -1));

        lblMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMascota.setText("Mascota");
        jPanel1.add(lblMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCedula.setText("Cedula");
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre ");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        lblRaza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRaza.setText("Raza");
        jPanel1.add(lblRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        lblEspecie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEspecie.setText("Especie");
        jPanel1.add(lblEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSexo.setText("Sexo");
        jPanel1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));
        jPanel1.add(txt_nombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 200, -1));
        jPanel1.add(txt_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 200, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gato", "Perro" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        btn_examinar.setText("Examinar");
        jPanel1.add(btn_examinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        lbl_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 150, 160));

        lblIcoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/RePer.png"))); // NOI18N
        jPanel1.add(lblIcoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 40, 40));

        lblIcoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ReMas.png"))); // NOI18N
        jPanel1.add(lblIcoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 50, 50));

        btn_registrar.setText("Registrar");
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        btn_cancelar.setText("Cancelar");
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 840, 550));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_examinar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblIcoM;
    private javax.swing.JLabel lblIcoP;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lblsApellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreM;
    private javax.swing.JTextField txt_pApellido;
    private javax.swing.JTextField txt_raza;
    private javax.swing.JTextField txt_sApellido;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

}
