/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;



/**
 *
 * @author Usuario
 */
public class VistaMascota extends javax.swing.JPanel {


    public VistaMascota() {
        initComponents();
    }

    public JButton getBtnBgestionMascota() {
        return btnBgestionMascota;
    }

    public void setBtnBgestionMascota(JButton btnBgestionMascota) {
        this.btnBgestionMascota = btnBgestionMascota;
    }

    public JButton getBtn_Vbuscar() {
        return btn_Vbuscar;
    }

    public void setBtn_Vbuscar(JButton btn_Vbuscar) {
        this.btn_Vbuscar = btn_Vbuscar;
    }

    public JButton getBtn_Vmodificar() {
        return btn_Vmodificar;
    }

    public void setBtn_Vmodificar(JButton btn_Vmodificar) {
        this.btn_Vmodificar = btn_Vmodificar;
    }

    public JLabel getLblBFoto() {
        return lblBFoto;
    }

    public void setLblBFoto(JLabel lblBFoto) {
        this.lblBFoto = lblBFoto;
    }

    public JPanel getPnlBmascota() {
        return pnlBmascota;
    }

    public void setPnlBmascota(JPanel pnlBmascota) {
        this.pnlBmascota = pnlBmascota;
    }

    public JPanel getPnlGmascota() {
        return pnlGmascota;
    }

    public void setPnlGmascota(JPanel pnlGmascota) {
        this.pnlGmascota = pnlGmascota;
    }

    public JScrollPane getScrBmascota() {
        return scrBmascota;
    }

    public void setScrBmascota(JScrollPane scrBmascota) {
        this.scrBmascota = scrBmascota;
    }

    public JTable getTblBmascota() {
        return tblBmascota;
    }

    public void setTblBmascota(JTable tblBmascota) {
        this.tblBmascota = tblBmascota;
    }

    public JTable getTblBpersona() {
        return tblBpersona;
    }

    public void setTblBpersona(JTable tblBpersona) {
        this.tblBpersona = tblBpersona;
    }

    public JTextField getTxtBpersona() {
        return txtBpersona;
    }

    public void setTxtBpersona(JTextField txtBpersona) {
        this.txtBpersona = txtBpersona;
    }

    public JLabel getLblBselecMas() {
        return lblBselecMas;
    }

    public void setLblBselecMas(JLabel lblBselecMas) {
        this.lblBselecMas = lblBselecMas;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_Vbuscar = new javax.swing.JButton();
        btn_Vmodificar = new javax.swing.JButton();
        pnlBmascota = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtBpersona = new javax.swing.JTextField();
        lbltext = new javax.swing.JLabel();
        lbltext2 = new javax.swing.JLabel();
        srlBpersona = new javax.swing.JScrollPane();
        tblBpersona = new javax.swing.JTable();
        lblBFoto = new javax.swing.JLabel();
        lblBselecMas = new javax.swing.JLabel();
        scrBmascota = new javax.swing.JScrollPane();
        tblBmascota = new javax.swing.JTable();
        btnBgestionMascota = new javax.swing.JButton();
        pnlGmascota = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        btn_Vbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar_32px.png"))); // NOI18N
        btn_Vbuscar.setToolTipText("");
        btn_Vbuscar.setFocusable(false);
        btn_Vbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Vbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_Vbuscar);

        btn_Vmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar_32px.png"))); // NOI18N
        btn_Vmodificar.setFocusable(false);
        btn_Vmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Vmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_Vmodificar);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 42));

        pnlBmascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblTitle.setText("Gestión Mascota");
        pnlBmascota.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 0, -1, -1));
        pnlBmascota.add(txtBpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 244, -1));

        lbltext.setText("Ingrese");
        pnlBmascota.add(lbltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lbltext2.setText("Cedula, nombre, apellido");
        pnlBmascota.add(lbltext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        tblBpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Papellido", "Sapellido"
            }
        ));
        srlBpersona.setViewportView(tblBpersona);

        pnlBmascota.add(srlBpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 220));
        pnlBmascota.add(lblBFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 170, 180));

        lblBselecMas.setText("Seleccione la mascota");
        pnlBmascota.add(lblBselecMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        tblBmascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Mascota", "Nombre", "Especie", "Raza"
            }
        ));
        scrBmascota.setViewportView(tblBmascota);

        pnlBmascota.add(scrBmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 490, 210));

        btnBgestionMascota.setText("Gestionar Mascota");
        pnlBmascota.add(btnBgestionMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        add(pnlBmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 862, 630));

        pnlGmascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(pnlGmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 630));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBgestionMascota;
    private javax.swing.JButton btn_Vbuscar;
    private javax.swing.JButton btn_Vmodificar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBFoto;
    private javax.swing.JLabel lblBselecMas;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbltext;
    private javax.swing.JLabel lbltext2;
    private javax.swing.JPanel pnlBmascota;
    private javax.swing.JPanel pnlGmascota;
    private javax.swing.JScrollPane scrBmascota;
    private javax.swing.JScrollPane srlBpersona;
    private javax.swing.JTable tblBmascota;
    private javax.swing.JTable tblBpersona;
    private javax.swing.JTextField txtBpersona;
    // End of variables declaration//GEN-END:variables
}
